artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/nxitik/car-pred-data/raw/main/car-pred-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/car-pred-data/CarPricesPrediction.csv
  STATUS_FILE : artifacts/data_validation/status.json

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion//car-pred-data/winequality-red.csv